name: Auto-Test

on:
  push:
    paths:
      - 'app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.4
          arguments: build -Prelease
      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: APK
          path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk